### ISSUE TITLE
Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by ayan-bloomscorp** [synopss/flex-layout-to-tailwind#1]
The library is throwing error as "Cannot find module 'fs-extra'" when `fltt` is run in the terminal.

<img width="808" alt="Screenshot 2024-01-19 at 9 23 06 PM" src="https://github.com/synopss/flex-layout-to-tailwind/assets/130522515/bef5fcdb-a20d-4c1e-a4fe-8c57d9e3cc24">

**Comment by ayan-bloomscorp** [comment]
It seems like the library has certain dependencies that are not getting installed by default. Solution to this problem is to install `fs-extra` separately globally.

`npm install -g fs-extra`
`npm install -g ignore` (another package that is not getting installed by default)

**Comment by ayan-bloomscorp** [comment]
As the issue is resolved from my end, I am closing this.

**Comment by seyfer** [comment]
I think, instead of closing, @synopss could fix it by adding the required dependencies to package.json

**Comment by synopss** [comment]
> I think, instead of closing, @synopss could fix it by adding the required dependencies to package.json

This was done in this PR #3

**Comment by seyfer** [comment]
@synopss I installed it just 2 days ago, and still had to install mentioned external dependencies manually.
`fs-extra` and `ignore`

**Comment by synopss** [comment]
> @synopss I installed it just 2 days ago, and still had to install mentioned external dependencies manually. `fs-extra` and `ignore`

Well, not sure what's going on then, cause as you can clearly see both packages are in the package.json file.
