### ISSUE TITLE
Feature Request: Option to install dependencies forcefully

### ISSUE THREAD

**Issue by ayan-bloomscorp** [synopss/flex-layout-to-tailwind#2]
I need an option to either skip tailwind setup as that is already in place or an option to install the dependencies forcefully to avoid situations as below.

<img width="1369" alt="Screenshot 2024-01-20 at 9 55 32 AM" src="https://github.com/synopss/flex-layout-to-tailwind/assets/130522515/3700ca4c-2e6c-4fb9-9015-317d340aeb91">

**Comment by ayan-bloomscorp** [comment]
I have already raised a PR(#3) for the same. Please do review it and publish it to npm, I have many projects to migrate.

**Comment by synopss** [comment]
That's a nice feature to add. I wrote a small comment on your PR, other than that, I really liked it.

**Comment by synopss** [comment]
fixed: #3
